version: '3.8'

services:
  family-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family-chat
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"  # Default to port 80
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - NODE_ENV=production
      - PORT=80
    user: "1001:1001"  # Run as non-root user
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - family-chat-network
    # Ensure Nginx runs in the foreground with debug logging
    command: ["nginx", "-g", "daemon off; error_log /dev/stderr debug;"]
    # Ensure proper shutdown handling
    stop_grace_period: 10s
    stop_signal: SIGQUIT
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    # Required writable directories for Nginx
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/log/nginx
      - /tmp
    # Ensure necessary capabilities for Nginx
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  family-chat-network:
    driver: bridge
